# Generated by Django 5.0 on 2023-12-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='meetup',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
