# Generated by Django 5.0 on 2023-12-25 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='meetup',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
