# Generated by Django 5.0 on 2023-12-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_meetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
